// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ8bhZQGgYqpIhqYEVM38pnnIQaRNATaw',
    appId: '1:884773953282:web:1796539f945ef6fd49ec1b',
    messagingSenderId: '884773953282',
    projectId: 'deaf-and-mute',
    authDomain: 'deaf-and-mute.firebaseapp.com',
    storageBucket: 'deaf-and-mute.appspot.com',
    measurementId: 'G-28TSZNMZXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2079B4JR68lVU6hdCf14in24Y3sZRhhQ',
    appId: '1:884773953282:android:50714ed944162c0249ec1b',
    messagingSenderId: '884773953282',
    projectId: 'deaf-and-mute',
    storageBucket: 'deaf-and-mute.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARoQ2bxJpGyDZjhXFS2tQdvwdDCtBVgx8',
    appId: '1:884773953282:ios:a8dfed4a1406f59a49ec1b',
    messagingSenderId: '884773953282',
    projectId: 'deaf-and-mute',
    storageBucket: 'deaf-and-mute.appspot.com',
    iosBundleId: 'com.example.deafMuteSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARoQ2bxJpGyDZjhXFS2tQdvwdDCtBVgx8',
    appId: '1:884773953282:ios:a8dfed4a1406f59a49ec1b',
    messagingSenderId: '884773953282',
    projectId: 'deaf-and-mute',
    storageBucket: 'deaf-and-mute.appspot.com',
    iosBundleId: 'com.example.deafMuteSystem',
  );
}
